---
# use shell rather than docker module
# to ensure osd disk prepare finishes before
# starting the next task
- name: manually prepare ceph "{{ osd_objectstore }}" non-containerized osd disk(s) with collocated osd data and journal
  command: "ceph-disk prepare {{ ceph_disk_cli_options }} {{ item.1 }}"
  with_together:
    - "{{ parted_results.results | default([]) }}"
    - "{{ devices }}"
  when:
    - not item.0.get("skipped")
    - item.0.get("rc", 0) != 0
    - not containerized_deployment
