---
- name: fail on unsupported system
  fail:
    msg: "System not supported {{ ansible_system }}"
  when:
    - ansible_system not in ['Linux']

- name: fail on unsupported architecture
  fail:
    msg: "Architecture not supported {{ ansible_architecture }}"
  when:
    - ansible_architecture not in ['x86_64', 'ppc64le', 'armv7l']

- name: fail on unsupported distribution
  fail:
    msg: "Distribution not supported {{ ansible_os_family }}"
  when:
    - ansible_os_family not in ['Debian', 'RedHat', 'ClearLinux']

- name: determine if node is registered with subscription-manager
  command: subscription-manager identity
  register: subscription
  changed_when: false
  failed_when: false
  check_mode: no
  when:
    - ansible_distribution == 'Red Hat Enterprise Linux'
    - ceph_repository == 'rhcs'
    - ceph_repository_type == 'cdn'

- name: fail on unsupported distribution for ubuntu cloud archive
  fail:
    msg: "Distribution not supported by Ubuntu Cloud Archive: {{ ansible_distribution }}"
  when:
    - ceph_repository == 'uca'
    - ansible_distribution != 'Ubuntu'

- name: fail on unsupported ansible version
  fail:
    msg: "Ansible version must be >= 2.3.x, please update!"
  when:
    - ansible_version.major|int < 2

- name: fail on unsupported ansible version
  fail:
    msg: "Ansible version must be >= 2.3.x, please update!"
  when:
    - ansible_version.major|int == 2
    - ansible_version.minor|int < 3

- name: fail if systemd is not present
  fail:
    msg: "Systemd must be present"
  when:
    - ansible_service_mgr != 'systemd'
